<?php

/**
 * Implements hook_menu().
 */
function autodialog_menu() {
  $items = array();

  $items['admin/config/system/autodialog'] = array(
    'title' => 'Autodialog',
    'description' => 'Autodialog settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('autodialog_settings_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'autodialog.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_page_delivery_callback_alter().
 */
function autodialog_page_delivery_callback_alter(&$callback) {
  if (_autodialog_check_request() && $callback == 'drupal_deliver_html_page') {
    $callback = 'autodialog_deliver';
  }
}

/**
 * Automodal delivery callback.
 */
function autodialog_deliver($page_callback_result) {
  $dialog_options = isset($_POST['autodialog_options']) ? $_POST['autodialog_options'] : array();
  if ($default_dialog_options = variable_get('autodialog_default_options')) {
    $dialog_options += drupal_json_decode($default_dialog_options);
  }

  $commands = array(
    array(
      'command' => 'autodialog',
      'title' => drupal_get_title(),
      'content' => drupal_render_page($page_callback_result),
      'options' => $dialog_options,
      'dialog_id' => check_plain($_POST['autodialog_link_id']) . '-dialog',
    ),
  );

  drupal_alter('autodialog_commands', $commands);

  ajax_deliver(array(
    '#type' => 'ajax',
    '#commands' => $commands,
  ));
}

/**
 * Implements hook_custom_theme().
 */
function autodialog_custom_theme() {
  if (_autodialog_check_request() && ($theme = ajax_base_page_theme())) {
    return $theme;
  }
}

/**
 * Implements hook_form_alter().
 */
function autodialog_form_alter(&$form, &$form_state, $form_id) {
  if (_autodialog_check_request() && !empty($_POST['autodialog_options']['ajax']) && module_exists('asaf')) {
    $form['#autodialog_link_id'] = $_POST['autodialog_link_id'];
    if (!empty($_POST['autodialog_options']['ajaxDisableRedirect'])) {
      $form['#autodialog_disable_redirect'] = TRUE;
    }
    asaf_prepare_form($form, $form_state);

    // Support Webforms
    if (
      strpos($form_id, 'webform_client_form_') === 0 &&
      isset($form['actions']['submit']['#pre_render']) &&
      ($key = array_search('webform_pre_render_remove_id', $form['actions']['submit']['#pre_render'])) !== FALSE
    ) {
      unset($form['actions']['submit']['#pre_render'][$key]);
    }
  }
}

/**
 * Implements hook_asaf_form_ajax_commands_alter().
 */
function autodialog_asaf_form_ajax_commands_alter(&$commands, $form, $form_state, $form_id) {
  // Disable redirect and reload
  if (!empty($form['#autodialog_disable_redirect'])) {
    $disabled = FALSE;
    foreach ($commands as $key => $command) {
      if ($command['command'] == 'asafRedirect' || $command['command'] == 'asafReload') {
        unset($commands[$key]);
        $disabled = TRUE;
        break;
      }
    }

    if ($disabled) {
      foreach ($commands as $key => $command) {
        // Search command adds status messages
        if ($command['command'] == 'insert' && $command['method'] == 'prepend' && !$command['selector']) {
          $commands[$key]['method'] = 'html';
          if ($commands[$key]['data'] == '') {
            $commands[$key]['data'] = t('Form submitted.');
          }
        }
      }
    }
  }

  // Centering dialog
  if (!empty($form['#autodialog_link_id'])) {
    $commands[] = array(
      'command' => 'autodialogCenter',
      'dialog_id' => check_plain($form['#autodialog_link_id']) . '-dialog',
    );
  }
}

/**
 * Implements hook_theme().
 */
function autodialog_theme() {
  return array(
    'html__autodialog' =>  array(
      'template' => 'templates/html--autodialog',
      'render element' => 'page',
    ),
    'page__autodialog' =>  array(
      'template' => 'templates/page--autodialog',
      'render element' => 'page',
    ),
    'region__autodialog' =>  array(
      'template' => 'templates/region--autodialog',
      'render element' => 'elements',
    ),
    'block__autodialog' =>  array(
      'template' => 'templates/block--autodialog',
      'render element' => 'elements',
    ),
  );
}

/**
 * Preprocess variables for html.tpl.php.
 */
function autodialog_preprocess_html(&$variables) {
  if (_autodialog_check_request()) {
    $variables['theme_hook_suggestions'][] = 'html__autodialog';
  }
}

/**
 * Preprocess variables for html.tpl.php.
 */
function autodialog_preprocess_page(&$variables) {
  if (_autodialog_check_request()) {
    $variables['theme_hook_suggestions'][] = 'page__autodialog';
  }
}

/**
 * Preprocess variables for region.tpl.php.
 */
function autodialog_preprocess_region(&$variables) {
  if (_autodialog_check_request()) {
    $variables['theme_hook_suggestions'][] = 'region__autodialog';
  }
}

/**
 * Preprocess variables for block.tpl.php.
 */
function autodialog_preprocess_block(&$variables) {
  if (_autodialog_check_request()) {
    $variables['theme_hook_suggestions'][] = 'block__autodialog';
  }
}

/**
 * Implements hook_page_alter().
 */
function autodialog_page_alter(&$page) {
  $paths = variable_get('autodialog_paths');
  if (!$paths || drupal_match_path(current_path(), $paths) || drupal_match_path(request_path(), $paths)) {
    drupal_add_library('system', 'drupal.ajax');
    drupal_add_library('system', 'ui.dialog');
    drupal_add_js(drupal_get_path('module', 'autodialog') . '/autodialog.js');
  }

  if (isset($page['page_top']['toolbar']) && _autodialog_check_request()) {
    $page['page_top']['toolbar']['#access'] = FALSE;
  }
}

/**
 * Return TRUE if if content should be shown in dialog.
 */
function _autodialog_check_request() {
  static $flag;

  if ($flag === NULL) {
    $flag = isset($_SERVER['HTTP_X_REQUESTED_WITH'])
      && $_SERVER['HTTP_X_REQUESTED_WITH'] == 'XMLHttpRequest'
      && !empty($_POST['autodialog_link_id']);

    // Decode options
    if ($flag && !empty($_POST['autodialog_options'])) {
      $_POST['autodialog_options'] = json_decode($_POST['autodialog_options'], TRUE);
    }
  }

  return $flag;
}
