<?php

// Файл с провайдеро-зависимыми функциями
module_load_include('inc', 'easyform', 'includes/common');
// Всё, что касается формы создания заявки
module_load_include('inc', 'easyform', 'includes/create_application_form');
// Форма подтверждения заявки
module_load_include('inc', 'easyform', 'includes/validate_application_form');

/**
 * Implements hook_menu().
 */

function easyform_menu() {
  $items['new'] = array(
    'title' => 'Создать заявку',
    'page callback' => 'drupal_get_form',
    //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
    'page arguments' => array('easyform_form'),
    //put the name of the form here
    'access arguments' => array('access content'),
//    'theme callback' => 'easyform_use_theme',
    'type' => MENU_CALLBACK,
  );

  $items['v'] = $items['v/%'] = array(
    'title' => 'Подтвердите заявку',
    'page callback' => 'drupal_get_form',
    //this is the function that will be called when the page is accessed.  for a form, use drupal_get_form
    'page arguments' => array('easyform_vform'),
    //put the name of the form here
    'access arguments' => array('access content'),
   // 'theme callback' => 'easyform_use_theme',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Returns theme name for this page
 */
/*function easyform_use_theme() {
  return 'vkv';
}*/
