<?php

// Файл с провайдеро-зависимыми функциями
module_load_include('inc', 'easyform', 'includes/common');
// Всё, что касается формы создания заявки
module_load_include('inc', 'easyform', 'includes/create_application_form');
// Форма подтверждения заявки
module_load_include('inc', 'easyform', 'includes/validate_application_form');

/**
 * Implements hook_menu().
 */
function easyform_menu() {
  $items['auction'] = array(
    'title' => 'Аукцион эвакуаторов - Заявка на эвакуацию',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('easyform_form'),
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  $items['v'] = $items['v/%'] = array(
    'title' => 'Подтвердите заявку',
    'page callback' => 'drupal_get_form',
    // This is the function that will be called when the page is accessed.
    // For a form, use drupal_get_form.
    'page arguments' => array('easyform_vform'),
    // Put the name of the form here.
    'access arguments' => array('access content'),
    // 'theme callback' => 'easyform_use_theme',
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_page_build().
 */
function easyform_page_build(&$page) {
  if (arg(0) == 'new') {
    $crumbs = array();
    $crumbs[] = l(t('Home'), '<front>');
    $crumbs[] = 'Заявка на эвакуацию';
    drupal_set_breadcrumb($crumbs);
  }
}
